# Generated by Django 3.2.5 on 2021-07-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('OrderId', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('OrderDate', models.CharField(max_length=30)),
                ('OrderTime', models.CharField(max_length=30)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerdetail')),
            ],
        ),
    ]
