# Generated by Django 3.2.5 on 2021-07-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('CustomerName', models.CharField(max_length=100)),
                ('CustomerId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('CustomerAddress', models.TextField(blank=True, null=True)),
                ('CustomerEmail', models.EmailField(max_length=55, unique=True)),
                ('CustomerPhone1', models.CharField(max_length=10)),
                ('CustomerPhone2', models.CharField(blank=True, max_length=10, null=True)),
                ('CustomerTargetDate', models.CharField(max_length=30)),
                ('CustomerLocationUrl', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
