# Generated by Django 3.2.5 on 2021-07-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customerdetail_customeremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='CustomerEmail',
            field=models.EmailField(blank=True, max_length=55, null=True),
        ),
    ]
